title: blomqu.ist
email: cameron@blomqu.ist
url: https://blomqu.ist

minima:
  social_links:
    github: camblomquist

theme: minima

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

keep_files:
  - images
  
exclude:
  - node_modules

timezone: America/New_York
